### ISSUE TITLE
There is something wrong with index.html

### ISSUE THREAD

**Issue by ghost** [cardozoaldama/landing-page#4]
I saw it with my own eyes! It has "ES" in their META, but I want to believe it you can put it in EN.

**Comment by cardozoaldama** [comment]
I think you are wrong, my old friend... I know this [index.html](https://github.com/cardozoaldama/landing-page/blob/29a41e1bad713a604dc7aee899904cdf9ec06ef3/index.html) has some Spanish in its content and the `<html lang="en">` it has in English mode, but there is no reason to change it.

**Comment by ghost** [comment]
Okay, Master. But when **Milestones**?

**Comment by cardozoaldama** [comment]
So soon, so soon...
